### ISSUE TITLE
Engine.evaluate() bug overwrites passed-in context

### ISSUE THREAD

**Issue by jdnier** [clevercss/clevercss#1]
The None check was forgotten, which causes context to always be reset to {}.

[Good grief, there appears to be no way to make github's comments display a unified diff.]

In Engine.evaluate(), change the "context = {}" line to "if context is None: context = {}.

```
 def evaluate(self, context=None):
     """Evaluate code."""
     expr = None
     if context is None:
         context = {}
     for key, value in context.iteritems():
         expr = self._parser.parse_expr(1, value)
         context[key] = expr
```

This bug causes the example at the bottom of the CleverCSS docs (http://sandbox.pocoo.org/clevercss/) to fail.

```
import clevercss
print clevercss.convert('''
body:
    background-color: $background_color
''', {'background_color: 'red.darken(10)'})
```

I checked Armin's original and it has the same problem.

There's a mailing list that looks active for the pocco sandbox projects. Did you not get any response there? I'm just wondering if they know about your patches. Thanks for your blog entry, which is how I discovered CleverCSS.

--David Niergarth

**Comment by jdnier** [comment]
I've seen some of your posts on pocco-libs mailing list, so that question is answered. On June 2nd, "Lasse" posted a similar patch to your thread on pocco-libs: 
http://groups.google.com/group/pocoo-libs/browse_thread/thread/559639a58fbc733a/71d9bc79b06a451f

**Comment by dziegler** [comment]
Oh wow, I didn't realize there was an open issue until just now. Sorry about that, didn't mean to ignore you. I applied the patch, thanks for letting me know about it!
