### ISSUE TITLE
can't redefine variables

### ISSUE THREAD

**Issue by tehfink** [clevercss/clevercss#10]
```
banner_desc_opacity = $banner_desc_opacity * 100
```

fails with:

```
variable "banner_title_opacity" defined twice
```

(this was necessary for silly ie workarounds)

**Comment by tehfink** [comment]
sub-issue:

here '.7' is interpreted as a string:

```
banner_desc_opacity = .7 * 100
```

`banner_desc_opacity` returns a string of 100 '.7':

```
.7 .7 .7 .7 .7 .7 .7 .7 .7 .7 .7 …
```

here '0.7' is interpreted as a decimal:

```
banner_desc_opacity = 0.7 * 100
```

`banner_desc_opacity` returns 100 \* '0.7':

```
70
```

is this intended behavior?

**Comment by jaredly** [comment]
I just spent a good chunk of time merging the work that people have done for clevercss so far (it's been pretty fragmented) and reorganizing the code (it was originally a monolithic 1600+ line file!). My fork is [over here](http://github.com/jabapyth/clevercss) if you want to check it out. -- there have been several syntax additions and many added unittests.

One of the bugs I fixed was that ".123" was interpreted as a string -- that is now fixed, and has a unittest associated w/ it.
As far as the original issue goes -- how do you expect this to behave? As far as I know, variables are static -- e.g the define time doesn't matter...

```
.boyd:
    border-width: $something

something = 10
```

turns into

```
.boyd {
  border-width: 10;
}
```

as you might imagine. Therefore I don't think redefining variables makes much sense.
