### ISSUE TITLE
small example does not work

### ISSUE THREAD

**Issue by deanmalmgren** [clevercss/clevercss#11]
I was playing around with CleverCSS this morning and I realized that the small example at the bottom of http://sandbox.pocoo.org/clevercss/ does not work.  Specifically, it is missing a single quote after background_color in the dictionary. I believe the example should read:

```
import clevercss
print clevercss.convert('''
body:
  background-color: $background_color
''', {'background_color': 'red.darken(10)'})
```

Also, for what it is worth, when I installed CleverCSS using easy_install, the example did not work even after fixing the syntax error.  The example does work with the current git version, though.

Thanks for a great package!  I am looking forward to using CleverCSS for my web development.

**Comment by jaredly** [comment]
I just spent a good chunk of time merging the work that people have done for clevercss so far (it's been pretty fragmented) and reorganizing the code (it was originally a monolithic 1600+ line file!). My fork is [over here](http://github.com/jabapyth/clevercss) if you want to check it out. -- there have been several syntax additions and many added unittests.

**Comment by encukou** [comment]
works now
