### ISSUE TITLE
Engine.convert mutates context

### ISSUE THREAD

**Issue by jdnier** [clevercss/clevercss#6]
When you pass in a dictionary as context to clevercss.convert(), clevercss mutates the items in your dictionary, turning string values into clevercss internal objects. This is surprising behavior, makes context unusable for passing into subsequent calls to convert(), and results in obtuse error messages. Here's an example:

```
>>> import clevercss
>>> template = """
... .highlight:
...     background-color: $highlight_color
... """
>>> context = {'highlight_color': '#FFFF00'}
>>> print clevercss.convert(template, context)
.highlight {
    background-color: #FFFF00;
}
>>> print context
{'highlight_color': Color(from_name=False, lineno=1, value=(255, 255, 0))}
>>> print clevercss.convert(template, context)
Traceback (most recent call last):
  ...
  File "clevercss.py", line 1399, in parse_expr
    s = s.rstrip(';')
AttributeError: 'Color' object has no attribute 'rstrip'
```

I've run into this a couple times and am surprised each time.

Rather than wrapping my contexts in dict() each time, here is a patch:

Change Engine.evaluate() from

```
def evaluate(self, context=None):
    """Evaluate code."""
    expr = None
    if not isinstance(context, dict):
        context = {}
    ...
```

to

```
def evaluate(self, context=None):
    """Evaluate code."""
    expr = None
    if context is None:
        context = {}
    else:
        context = context.copy()
    ...
```

I'll argue that the isinstance() check that you added in the last patch is not ideal. Armin was using None as a compile-time default; if what's passed in is not None, the function should accept it. Right now, if what's passed is not a dictionary, the your version silently ignores it, replacing it with {}. See http://docs.python.org/reference/compound_stmts.html#index-769 for an explanation of this usage of None as a default value.

Also, the CleverCSS docs explain that context should be a dictionary.

```
"If you want to provide defaults for variables you can pass it a dict of strings 
 with valid CleverCSS expressions."
```

So, if something non-dict-like gets passed in, I think it's better behavior to let an exception get raised.

I'll submit this patch to the pocco list, although Armin doesn't seem to have gotten back to CleveCSS yet.

**Comment by encukou** [comment]
This has been fixed in the more recent branches.

**Comment by jdnier** [comment]
Do you know where these more-recent branches live? I can't find any more recent versions.

**Comment by encukou** [comment]
Clicking Github's _Network_ tab will give you an overview.
I've recently pulled these together in my branch: https://github.com/encukou/clevercss/
