### ISSUE TITLE
I read somewhere that you can do an @include of a ccss file...

### ISSUE THREAD

**Issue by benjamindell** [clevercss/clevercss#8]
... but this doesnt seem to work? I'm basically just trying to find a way to share variables across 3 ccss files. Any suggestions?

**Comment by tehfink** [comment]
i would really love this functionality

**Comment by jaredly** [comment]
I just spent a good chunk of time merging the work that people have done for clevercss so far (it's been pretty fragmented) and reorganizing the code (it was originally a monolithic 1600+ line file!). My fork is [over here](http://github.com/jabapyth/clevercss) if you want to check it out. -- there have been several syntax additions and many added unittests.

One of these syntax additions is the [@import command](http://github.com/jabapyth/clevercss/commit/04536763f98bf5285194595a39e21c41d7c63b1a).

example:

```
// main.ccss
@import(other.ccss)
body:
   color: $color
```

and in the same directory:

```
// other.ccss
color = red
```
